# docker-compose-sasl.yml
services:
  kafka-1:
    ports:
      - "29092:9094"
    volumes:
      - ./scripts/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Dzookeeper.sasl.client=false"

      KAFKA_ZOOKEEPER_SET_ACL: "false"
      KAFKA_ZOOKEEPER_SASL_CLIENT: "false"

      KAFKA_CUB_ZK_TIMEOUT: "120"
      KAFKA_CUB_KAFKA_TIMEOUT: "120"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_SSL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092,SSL://kafka-1:9093,SASL_SSL://kafka-1:9094"

      KAFKA_LISTENER_NAME_SASL_SSL_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_LISTENER_NAME_SASL_SSL_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret-123";'

  kafka-2:
    ports:
      - "29093:9094"
    volumes:
      - ./scripts/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Dzookeeper.sasl.client=false"

      KAFKA_ZOOKEEPER_SET_ACL: "false"
      KAFKA_ZOOKEEPER_SASL_CLIENT: "false"

      KAFKA_CUB_ZK_TIMEOUT: "120"
      KAFKA_CUB_KAFKA_TIMEOUT: "120"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_SSL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092,SSL://kafka-2:9093,SASL_SSL://kafka-2:9094"

      KAFKA_LISTENER_NAME_SASL_SSL_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_LISTENER_NAME_SASL_SSL_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret-123";'

  kafka-3:
    ports:
      - "29094:9094"
    volumes:
      - ./scripts/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:ro
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Dzookeeper.sasl.client=false"

      KAFKA_ZOOKEEPER_SET_ACL: "false"
      KAFKA_ZOOKEEPER_SASL_CLIENT: "false"

      KAFKA_CUB_ZK_TIMEOUT: "120"
      KAFKA_CUB_KAFKA_TIMEOUT: "120"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_SSL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9092,SSL://kafka-3:9093,SASL_SSL://kafka-3:9094"

      KAFKA_LISTENER_NAME_SASL_SSL_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_SASL_ENABLED_MECHANISMS: "SCRAM-SHA-256"
      KAFKA_LISTENER_NAME_SASL_SSL_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret-123";'

  kafka-sasl-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-sasl-init
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    environment:
      KAFKA_APP_USER: "app"
      KAFKA_APP_PASSWORD: "app-secret-123"
      KAFKA_ADMIN_USER: "admin"
      KAFKA_ADMIN_PASSWORD: "admin-secret-123"
      TOPIC: "events"
    volumes:
      - ./scripts/kafka-sasl-init.sh:/work/kafka-sasl-init.sh:ro
    entrypoint: ["/bin/bash", "/work/kafka-sasl-init.sh"]
    restart: "no"
