services:
  kafka-1:
    environment:
      # inter-broker over TLS
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""

      # IMPORTANT for .p12
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"

      # force mTLS on SSL listener (optional but recommended)
      KAFKA_LISTENER_NAME_SSL_SSL_CLIENT_AUTH: "required"

  kafka-2:
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_LISTENER_NAME_SSL_SSL_CLIENT_AUTH: "required"

  kafka-3:
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_LISTENER_NAME_SSL_SSL_CLIENT_AUTH: "required"
