services:
  kafka-1:
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  kafka-2:
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  kafka-3:
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: "SSL"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
